import { Feather } from "@expo/vector-icons";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { BookCover } from "@/components/BookCover";
import { Screen } from "@/components/Screen";
import { useLibrary } from "@/context/LibraryContext";
import { useColors } from "@/hooks/useColors";

export default function Catalog() {
  const colors = useColors(); const { books } = useLibrary(); const [query, setQuery] = useState("");
  const results = useMemo(() => books.filter((book) => `${book.title} ${book.authors} ${book.subjects}`.toLowerCase().includes(query.toLowerCase())), [books, query]);
  return <Screen><View style={styles.heading}><View><Text style={[styles.kicker, { color: colors.primary }]}>YOUR LIBRARY</Text><Text style={[styles.title, { color: colors.foreground }]}>Catalog</Text></View><Pressable testID="catalog-add" onPress={() => router.push("/add-book")} style={[styles.add, { backgroundColor: colors.primary }]}><Feather name="plus" size={20} color={colors.primaryForeground} /></Pressable></View><View style={[styles.search, { backgroundColor: colors.card, borderColor: colors.border }]}><Feather name="search" size={18} color={colors.mutedForeground} /><TextInput testID="catalog-search" value={query} onChangeText={setQuery} placeholder="Search title, author, or subject" placeholderTextColor={colors.mutedForeground} style={[styles.input, { color: colors.foreground }]} /></View><Text style={[styles.count, { color: colors.mutedForeground }]}>{results.length} {results.length === 1 ? "book" : "books"}</Text>{results.length === 0 ? <View style={styles.empty}><Feather name="book-open" size={28} color={colors.primary} /><Text style={[styles.emptyTitle, { color: colors.foreground }]}>No books found</Text><Text style={[styles.emptyText, { color: colors.mutedForeground }]}>Try another search or add a new book.</Text></View> : results.map((book) => <Pressable key={book.id} onPress={() => router.push({ pathname: "/book/[id]", params: { id: book.id } })} style={styles.book}><BookCover uri={book.coverUrl} title={book.title} size={82} /><View style={styles.flex}><Text style={[styles.bookTitle, { color: colors.foreground }]}>{book.title}</Text><Text style={[styles.author, { color: colors.mutedForeground }]}>{book.authors}</Text><View style={styles.meta}><View style={[styles.pill, { backgroundColor: book.placement ? colors.accent : book.shelfId ? colors.secondary : colors.muted }]}><Text style={[styles.pillText, { color: book.placement ? colors.primary : colors.mutedForeground }]}>{book.placement ? "Placed" : book.shelfId ? "Needs placement" : "Not assigned"}</Text></View><Text style={[styles.subject, { color: colors.mutedForeground }]}>{book.subjects.split(",")[0]}</Text></View></View><Feather name="chevron-right" size={18} color={colors.mutedForeground} /></Pressable>)}</Screen>;
}
const styles = StyleSheet.create({ heading: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end" }, kicker: { fontSize: 11, fontWeight: "700", letterSpacing: 1.6 }, title: { fontSize: 34, fontWeight: "700", marginTop: 5 }, add: { width: 45, height: 45, borderRadius: 14, alignItems: "center", justifyContent: "center" }, search: { borderWidth: 1, height: 50, borderRadius: 15, flexDirection: "row", alignItems: "center", paddingHorizontal: 14, gap: 10 }, input: { flex: 1, fontSize: 14 }, count: { fontSize: 12 }, book: { flexDirection: "row", gap: 14, alignItems: "center", paddingVertical: 5 }, flex: { flex: 1 }, bookTitle: { fontSize: 16, fontWeight: "700" }, author: { fontSize: 13, marginTop: 5 }, meta: { flexDirection: "row", gap: 8, alignItems: "center", marginTop: 10 }, pill: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 7 }, pillText: { fontSize: 10, fontWeight: "700" }, subject: { fontSize: 11 }, empty: { alignItems: "center", gap: 10, paddingTop: 85 }, emptyTitle: { fontSize: 18, fontWeight: "700" }, emptyText: { fontSize: 14 } });