import { Feather } from "@expo/vector-icons";
import { router, useLocalSearchParams } from "expo-router";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { Screen } from "@/components/Screen";
import { useLibrary } from "@/context/LibraryContext";
import { useColors } from "@/hooks/useColors";

export default function Locate() {
  const colors = useColors(); const { id } = useLocalSearchParams<{ id: string }>(); const { books, shelf } = useLibrary(); const book = books.find((item) => item.id === id);
  if (!book) return <Screen><Text style={{ color: colors.foreground }}>Book not found.</Text></Screen>;
  return <View style={[styles.root, { backgroundColor: "#0b191e" }]}><View style={styles.top}><Pressable onPress={() => router.back()} style={styles.icon}><Feather name="x" size={22} color="#fff" /></Pressable><View style={styles.tracking}><View style={styles.greenDot} /><Text style={styles.trackingText}>{shelf.mapped ? "Shelf found" : "Preview mode"}</Text></View><View style={styles.icon} /></View><View style={styles.grid}><View style={styles.shelfLine} /><View style={styles.bookmark}><Feather name="navigation" size={28} color={colors.primary} /></View><Text style={styles.direction}>Book location</Text></View><View style={styles.bottom}><Text style={styles.kicker}>YOU’RE LOOKING FOR</Text><Text style={styles.bookTitle}>{book.title}</Text><Text style={styles.author}>{book.authors}</Text><Text style={styles.note}>{shelf.mapped ? "Move slowly and keep the shelf in view. The marker points to the stored position." : "Set up your shelf to enable persistent AR locating."}</Text><Pressable onPress={() => router.back()} style={[styles.done, { backgroundColor: colors.primary }]}><Text style={{ color: colors.primaryForeground, fontSize: 16, fontWeight: "700" }}>Done</Text></Pressable></View></View>;
}
const styles = StyleSheet.create({ root: { flex: 1 }, top: { paddingTop: 58, paddingHorizontal: 20, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, icon: { width: 40, height: 40, borderRadius: 20, backgroundColor: "rgba(255,255,255,.12)", alignItems: "center", justifyContent: "center" }, tracking: { flexDirection: "row", alignItems: "center", gap: 7, backgroundColor: "rgba(255,255,255,.12)", paddingHorizontal: 12, paddingVertical: 8, borderRadius: 20 }, greenDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: "#7fd7a8" }, trackingText: { color: "#fff", fontSize: 12, fontWeight: "700" }, grid: { flex: 1, alignItems: "center", justifyContent: "center" }, shelfLine: { width: "76%", height: 8, backgroundColor: "#b8814c", borderRadius: 4, transform: [{ perspective: 400 }, { rotateX: "8deg" }] }, bookmark: { width: 72, height: 72, borderRadius: 36, backgroundColor: "rgba(244,182,109,.18)", borderWidth: 1, borderColor: "#f4b66d", alignItems: "center", justifyContent: "center", marginBottom: 15 }, direction: { color: "#f4b66d", fontSize: 14, fontWeight: "700" }, bottom: { backgroundColor: "#12282e", borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 24, paddingBottom: 38, gap: 8 }, kicker: { color: "#85a09e", fontSize: 10, fontWeight: "700", letterSpacing: 1.5 }, bookTitle: { color: "#fff", fontSize: 23, fontWeight: "700", marginTop: 3 }, author: { color: "#b6c9c5", fontSize: 14 }, note: { color: "#85a09e", fontSize: 13, lineHeight: 19, marginTop: 8 }, done: { height: 49, borderRadius: 15, alignItems: "center", justifyContent: "center", marginTop: 10 } });