import { Feather } from "@expo/vector-icons";
import { router } from "expo-router";
import { useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { Screen } from "@/components/Screen";
import { useLibrary } from "@/context/LibraryContext";
import { useColors } from "@/hooks/useColors";

export default function ShelfSetup() {
  const colors = useColors(); const { shelf, setupShelf } = useLibrary(); const [name, setName] = useState(shelf.name);
  const save = async () => { if (!name.trim()) return Alert.alert("Name your shelf", "Give this bookcase level a name."); await setupShelf(name.trim()); Alert.alert("Shelf mapped", "Your shelf origin is saved locally. In the native iOS build, this step will use ARKit world mapping.", [{ text: "Done", onPress: () => router.back() }]); };
  return <Screen><View style={styles.top}><Pressable onPress={() => router.back()}><Feather name="arrow-left" size={22} color={colors.foreground} /></Pressable><Text style={[styles.topTitle, { color: colors.foreground }]}>Shelf setup</Text><View style={{ width: 22 }} /></View><View style={[styles.hero, { backgroundColor: colors.accent }]}><Feather name="layers" size={38} color={colors.primary} /><Text style={[styles.heroTitle, { color: colors.foreground }]}>{shelf.mapped ? "Your shelf is mapped" : "Map your bookcase level"}</Text><Text style={[styles.heroText, { color: colors.mutedForeground }]}>Slowly pan across the full level so your iPhone can recognize it later. Choose a clear, well-lit view.</Text></View><Text style={[styles.label, { color: colors.mutedForeground }]}>SHELF NAME</Text><TextInput value={name} onChangeText={setName} placeholder="Living room bookcase" placeholderTextColor={colors.mutedForeground} style={[styles.input, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.card }]} /><View style={[styles.steps, { borderColor: colors.border }]}><Step n="1" text="Pan slowly across the bookcase" colors={colors} /><Step n="2" text="Keep the phone steady for a moment" colors={colors} /><Step n="3" text="Tap Set shelf origin" colors={colors} /></View><Pressable testID="set-shelf-origin" onPress={save} style={[styles.button, { backgroundColor: colors.primary }]}><Feather name="crosshair" size={18} color={colors.primaryForeground} /><Text style={[styles.buttonText, { color: colors.primaryForeground }]}>{shelf.mapped ? "Re-scan shelf" : "Set shelf origin"}</Text></Pressable></Screen>;
}
function Step({ n, text, colors }: { n: string; text: string; colors: ReturnType<typeof useColors> }) { return <View style={styles.step}><View style={[styles.number, { backgroundColor: colors.primary }]}><Text style={{ color: colors.primaryForeground, fontWeight: "700" }}>{n}</Text></View><Text style={[styles.stepText, { color: colors.foreground }]}>{text}</Text></View>; }
const styles = StyleSheet.create({ top: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, topTitle: { fontSize: 15, fontWeight: "700" }, hero: { borderRadius: 22, padding: 24, alignItems: "center", gap: 12, marginTop: 16 }, heroTitle: { fontSize: 21, fontWeight: "700", textAlign: "center" }, heroText: { fontSize: 14, lineHeight: 21, textAlign: "center" }, label: { fontSize: 11, fontWeight: "700", letterSpacing: 1.3, marginTop: 8 }, input: { height: 50, borderWidth: 1, borderRadius: 14, paddingHorizontal: 14, fontSize: 15 }, steps: { borderWidth: 1, borderRadius: 17, padding: 16, gap: 16 }, step: { flexDirection: "row", alignItems: "center", gap: 12 }, number: { width: 28, height: 28, borderRadius: 14, alignItems: "center", justifyContent: "center" }, stepText: { fontSize: 14 }, button: { height: 52, borderRadius: 16, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 9 }, buttonText: { fontSize: 16, fontWeight: "700" } });